### ISSUE TITLE
[Question] Is the bacteria dataset updated? (July 2023)

### ISSUE THREAD

**Issue by MatteoRiva95** [ropensci/biomartr#115]
Hello everyone,

I am running the help session for getGenome function and I found out this description for the parameter "skip_criteria":

Due to its enormous dataset size (> 700MB as of July 2023)...

Is the dataset updated or is it still from July 2023?
I am using the biomartr 1.0.7 version. Should I update the package?

Thank you so much in advance!

**Comment by HajkD** [comment]
Hi @MatteoRiva95 

The date July 2023 only refers to the dataset size in that month. Since biomartr interfaces with the online databases which are always up to date, this dataset size is likely much bigger now more than one year later. So you will always retrieve the most recent datasets.

I hope this helps!

Cheers,
Hajk
