### ISSUE TITLE
Question about mapping SNPs to Genes with biomartR

### ISSUE THREAD

**Issue by arbet003** [ropensci/biomartr#14]
Hello,

I am trying to use your biomartR package to map each SNP to all genes within 50kb (upstream or downstream) of the SNP.  Here is my code:

```
library("biomaRt")
grch37.snp = useMart(biomart="ENSEMBL_MART_SNP", host="grch37.ensembl.org", path="/biomart/martservice",dataset="hsapiens_snp")
 
grch37 = useMart(biomart="ENSEMBL_MART_ENSEMBL", host="grch37.ensembl.org", path="/biomart/martservice", dataset="hsapiens_gene_ensembl")
 
BMsnpinfo <- getBM(attributes = c("refsnp_id", "ensembl_gene_stable_id"), 
                filters = "snp_filter", 
                values = snplist, 
                mart = grch37.snp)
```

where "snplist" is an R vector with a bunch of SNP "rs" numbers.  The output object "BMsnpinfo" tells me which gene each SNP is mapped too.  My questions are as follows:

1) By default, how far away from a gene does a SNP need to be in order to be mapped to that gene?  10kb? 50kb? 100kb?

2) Suppose I want to map each SNP to _all_ genes within 50kb upstream or downstream of the SNP.  Is it possible to do this with the biomartR package?

Thanks

**Comment by HajkD** [comment]
Hi @arbet003,

Sorry for my late response.

Would you mind posting this question on [Biostars](https://www.biostars.org/) so that we can discuss it there also with a broader audience? Since this is a biology related question rather than a tool related one, it might be more appropriate there and I am happy to contribute to the discussion there.

Many thanks,
Hajk
