### ISSUE TITLE
Immediate problem on install - getMarts crashing

### ISSUE THREAD

**Issue by aleighgreen** [ropensci/biomartr#36]
Hello, 

Just installed and trying to go through the tutorial steps, but running into an issue right away. 

```
biomartr::getMarts()
Error in getSubMarts(submarts[i]) : Service Unavailable (HTTP 503).
```

**Comment by HajkD** [comment]
Hi @aleighgreen 

Many thanks for contacting me.

I just ran the command and it works perfectly fine.
Here the output:

```r
# A tibble: 15 x 2
   mart                  version                       
   <chr>                 <chr>                         
 1 ENSEMBL_MART_ENSEMBL  Ensembl Genes 95              
 2 ENSEMBL_MART_MOUSE    Mouse strains 95              
 3 ENSEMBL_MART_SEQUENCE Sequence                      
 4 ENSEMBL_MART_ONTOLOGY Ontology                      
 5 ENSEMBL_MART_GENOMIC  Genomic features 95           
 6 ENSEMBL_MART_SNP      Ensembl Variation 95          
 7 ENSEMBL_MART_FUNCGEN  Ensembl Regulation 95         
 8 plants_mart           Ensembl Plants Genes 42       
 9 plants_variations     Ensembl Plants Variations 42  
10 fungi_mart            Ensembl Fungi Genes 42        
11 fungi_variations      Ensembl Fungi Variations 42   
12 protists_mart         Ensembl Protists Genes 42     
13 protists_variations   Ensembl Protists Variations 42
14 metazoa_mart          Ensembl Metazoa Genes 42      
15 metazoa_variations    Ensembl Metazoa Variations 42 
```

It some instances the BioMart servers are down due to maintenance etc.
Could you please provide me some details about the system you work with and
how you access the internet (maybe a firewall that blocks programmatic access to other servers?)?

Does the same error occur when you re-run it on different days?

Best wishes,
Hajk

**Comment by aleighgreen** [comment]
I would guess the servers were down, it was the first time I tried running it yesterday, working perfectly fine now. Maybe worth adding a slightly more informative error message in this instance. Thanks

**Comment by HajkD** [comment]
Happy to hear that it is resolved now. Sure, I can add a more detailed error message in case this happens. Cheers :-)
